### ISSUE TITLE
Add samples about dataset iteration

### ISSUE THREAD

**Issue by mincong-h** [jingwen-z/python-playground#6]
It would be helpful to add samples about different kinds of dataset iteration, e.g. DataFrame, Series, Index, dictionary.

**Comment by jingwen-z** [comment]
[Python for loop](https://github.com/jingwen-z/python-playground/blob/master/basic/python_for_loop.ipynb)
[Python while loop](https://github.com/jingwen-z/python-playground/blob/master/basic/python_while_loop.ipynb)
